import { useState, useEffect } from 'react';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import { CssBaseline, NextUIProvider } from '@nextui-org/react';
import Spinner from '@jpe-reader/components/Molecules/Spinner/Spinner';
import Navbar from '@jpe-reader/components/Organisms/Navbar';
import WrapperApp from '@jpe-reader/components/Organisms/WrapperApp';
import WrapperJune from '@jpe-reader/components/Organisms/WrapperJune';

import 'normalize.css';
import '../styles/globals.css';
import '@jpe-reader/styles/variables-globals.css';

function MyApp(AppProps: AppProps) {
  const [isRender, setIsRender] = useState<boolean>(false);

  useEffect(() => {
    if (window) setIsRender(true);
  }, []);

  if (!isRender)
    return (
      <div className="container-spinner">
        <Spinner />
      </div>
    );

  return (
    <NextUIProvider>
      <WrapperApp>
        <Head>
          <meta charSet="utf-8" />
          <meta
            name="viewport"
            content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"
          />
          <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
          <meta name="description" content="Generated by create next app" />
          <meta name="keywords" content="Keywords" />

          <link rel="manifest" href="/manifest.json" />
          <link rel="icon" href="/favicon.ico" />
          <link
            href="/icons/favicon-16x16.png"
            rel="icon"
            type="image/png"
            sizes="16x16"
          />
          <link
            href="/icons/favicon-32x32.png"
            rel="icon"
            type="image/png"
            sizes="32x32"
          />
          <link rel="apple-touch-icon" href="/apple-icon.png"></link>
          <meta name="theme-color" content="#317EFB" />
        </Head>
        <CssBaseline />
        <Navbar />
        <WrapperJune {...AppProps} />
      </WrapperApp>
    </NextUIProvider>
  );
}

export default MyApp;
