import type { NextPage } from 'next';
import Head from 'next/head';
import Button from '@jpe-reader/components/Atoms/Button';
import styles from '../styles/Home.module.css';
import { Portal } from '@jpe-reader/components/Organisms/Portal';
import { useToggle } from '@jpe-reader/hooks/useToggle';

const Home: NextPage = () => {
  const { toggle, handleToggle } = useToggle();

  return (
    <div className={styles.container}>
      <Head>
        <title>JEP-Reader</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button onClick={handleToggle}>button</Button>
      <Portal isVisible={toggle} onClose={handleToggle}>
        <h3>holaaa</h3>
      </Portal>
    </div>
  );
};

export default Home;
